### ISSUE TITLE
player-inventory.js:1077 Uncaught TypeError: window.makePermalink is not a function

### ISSUE THREAD

**Issue by Charles-Jones-Unicon** [le-jeu/iitc-plugins#6]
I get the following error when I try to use the Player Inventory script:

player-inventory.js:1077 Uncaught TypeError: window.makePermalink is not a function
    at PortalKeyLink (player-inventory.js:1077:18)
    at jsx (player-inventory.js:733:45)
    at player-inventory.js:1099:17
    at Array.map (<anonymous>)
    at KeysTable (player-inventory.js:1097:20)
    at jsx (player-inventory.js:733:45)
    at InventoryTables (player-inventory.js:1189:19)
    at jsx (player-inventory.js:733:45)
    at buildInventoryHTML (player-inventory.js:1424:21)
    at displayInventory (player-inventory.js:1447:21)

**Comment by le-jeu** [comment]
That's weird since `window.makePermalink` is a function from IITC.
Can you provide the version of:
 - IITC
 - Plugin loader (and name) (greasemonkey, iitc button...) 
 - Browser

**Comment by Charles-Jones-Unicon** [comment]
> That's weird since `window.makePermalink` is a function from IITC.

That was it! I was running an old version of IITC (0.26)!
Plugin is working fine now. Thank you for your work!
